const target = db.getSiblingDB('kamehadb');

['comments', 'posts', 'users', 'organizations'].forEach((collection) => {
  target[collection].drop();
});

target.organizations.insertMany([
  { _id: 1, name: 'Acme Inc', slug: 'acme', created_at: new Date() },
  { _id: 2, name: 'Globex Corp', slug: 'globex', created_at: new Date() },
  { _id: 3, name: 'Initech', slug: 'initech', created_at: new Date() },
  { _id: 4, name: 'Umbrella Co', slug: 'umbrella', created_at: new Date() },
]);

target.users.insertMany([
  { _id: 1, org_id: 1, name: 'Alice', email: 'alice@acme.com', role: 'admin', created_at: new Date() },
  { _id: 2, org_id: 1, name: 'Bob', email: 'bob@acme.com', role: 'member', created_at: new Date() },
  { _id: 3, org_id: 1, name: 'Charlie', email: 'charlie@acme.com', role: 'member', created_at: new Date() },
  { _id: 4, org_id: 2, name: 'Carol', email: 'carol@globex.com', role: 'admin', created_at: new Date() },
  { _id: 5, org_id: 2, name: 'David', email: 'david@globex.com', role: 'member', created_at: new Date() },
  { _id: 6, org_id: 2, name: 'Eve', email: 'eve@globex.com', role: 'member', created_at: new Date() },
  { _id: 7, org_id: 3, name: 'Frank', email: 'frank@initech.com', role: 'admin', created_at: new Date() },
  { _id: 8, org_id: 3, name: 'Grace', email: 'grace@initech.com', role: 'member', created_at: new Date() },
  { _id: 9, org_id: 4, name: 'Hank', email: 'hank@umbrella.com', role: 'admin', created_at: new Date() },
  { _id: 10, org_id: 4, name: 'Ivy', email: 'ivy@umbrella.com', role: 'member', created_at: new Date() },
]);

target.posts.insertMany([
  {
    _id: 1,
    user_id: 1,
    title: 'Hello World',
    body: 'This is the first post.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 2,
    user_id: 1,
    title: 'Getting Started with SQL',
    body: 'SQL is a powerful language for managing data.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 3,
    user_id: 1,
    title: 'Advanced Queries',
    body: 'Learn about joins, subqueries, and CTEs.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 4,
    user_id: 2,
    title: 'My First Draft',
    body: 'Not published yet.',
    published: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 5,
    user_id: 2,
    title: 'Tips for Beginners',
    body: 'Start with the basics and practice daily.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 6,
    user_id: 3,
    title: 'Database Design',
    body: 'Normalization and indexing explained.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 7,
    user_id: 4,
    title: 'Company Announcement',
    body: 'Welcome to Globex!',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 8,
    user_id: 4,
    title: 'Q4 Results',
    body: 'Quarterly performance review.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 9,
    user_id: 5,
    title: 'Tech Stack Overview',
    body: 'Our technology choices for 2026.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 10,
    user_id: 6,
    title: 'Remote Work Guide',
    body: 'Best practices for distributed teams.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 11,
    user_id: 7,
    title: 'Project Alpha',
    body: 'Introducing our new flagship product.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 12,
    user_id: 8,
    title: 'Team Building',
    body: 'Activities that bring people together.',
    published: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 13,
    user_id: 9,
    title: 'Security Best Practices',
    body: 'Keeping your data safe.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: 14,
    user_id: 10,
    title: 'Onboarding Checklist',
    body: 'A guide for new hires.',
    published: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
]);

target.comments.insertMany([
  { _id: 1, post_id: 1, user_id: 2, body: 'Great post!', created_at: new Date() },
  { _id: 2, post_id: 1, user_id: 3, body: 'Thanks for sharing.', created_at: new Date() },
  { _id: 3, post_id: 2, user_id: 2, body: 'Very helpful, thanks!', created_at: new Date() },
  { _id: 4, post_id: 2, user_id: 4, body: 'Well written.', created_at: new Date() },
  { _id: 5, post_id: 3, user_id: 5, body: 'Could you add more examples?', created_at: new Date() },
  { _id: 6, post_id: 3, user_id: 6, body: 'This cleared up a lot of confusion.', created_at: new Date() },
  { _id: 7, post_id: 5, user_id: 1, body: 'Great tips for newcomers.', created_at: new Date() },
  { _id: 8, post_id: 6, user_id: 7, body: 'Excellent explanation of B-tree indexes.', created_at: new Date() },
  { _id: 9, post_id: 7, user_id: 8, body: 'Exciting news!', created_at: new Date() },
  { _id: 10, post_id: 9, user_id: 9, body: 'Interesting tech choices.', created_at: new Date() },
  { _id: 11, post_id: 10, user_id: 10, body: 'Saving this for my team.', created_at: new Date() },
  { _id: 12, post_id: 11, user_id: 1, body: 'Can not wait for the launch!', created_at: new Date() },
  { _id: 13, post_id: 13, user_id: 2, body: 'This should be required reading.', created_at: new Date() },
  { _id: 14, post_id: 14, user_id: 3, body: 'Perfect timing, we just hired two people.', created_at: new Date() },
]);
